package com.mrashidcit.project2_localpeerconnection.presentation.call

import android.app.Application
import android.util.Log
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.mrashidcit.project2_localpeerconnection.model.PeerConnectionState
import com.mrashidcit.project2_localpeerconnection.webrtc.PeerConnectionManager
import com.mrashidcit.project2_localpeerconnection.webrtc.WebRtcManager
import kotlinx.coroutines.launch
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import org.webrtc.AudioTrack
import org.webrtc.IceCandidate
import org.webrtc.PeerConnection
import org.webrtc.VideoTrack

/**
 * LocalPeerConnectionViewModel - PART 9 & 17 of the learning project.
 *
 * This is where the ENTIRE 18-step flow described in the project brief lives,
 * in order, as plain sequential suspend function calls. This is deliberate:
 * the brief explicitly says "do not hide the WebRTC flow" - so instead of
 * spreading step 6 (createOffer) and step 9 (setRemoteDescription on B)
 * across different files/classes, every step below reads top-to-bottom in
 * the exact order WebRTC actually performs it.
 *
 * PART 9 - "TRANSFER OFFER TO PEER B" / signaling simulation:
 * A real app would serialize a SessionDescription/IceCandidate to JSON,
 * send it over a WebSocket to a signaling server, which forwards it to the
 * other device, which deserializes it back into a SessionDescription/
 * IceCandidate object. Here, there is no other device and no network - so
 * "sending" an offer from Peer A to Peer B is simply passing the exact same
 * Kotlin `SessionDescription` object from `peerConnectionA.createOffer()`
 * straight into `peerConnectionB.setRemoteDescription(offer)`. Every place
 * that hand-off happens is marked with a comment below - look for
 * "SIGNALING SIMULATION".
 */
class LocalPeerConnectionViewModel(application: Application) : AndroidViewModel(application) {

    companion object {
        private const val LOCAL_STREAM_ID = "LOCAL_STREAM"
    }

    private val tag = LocalPeerConnectionViewModel::class.java.simpleName

    private val webRtcManager = WebRtcManager(application)

    /** Exposed so the Compose screen can init its SurfaceViewRenderer with the same GL context WebRTC uses internally. */
    val eglBaseContext get() = webRtcManager.eglBaseContext

    private var peerConnectionA: PeerConnectionManager? = null
    private var peerConnectionB: PeerConnectionManager? = null

    // ICE candidates generated by each peer, queued here until the user
    // presses "Exchange ICE" - see PART 12 in PeerConnectionManager.kt for
    // why this queueing step is a deliberate teaching choice rather than
    // auto-forwarding candidates the instant they are generated.
    private val candidatesFromA = mutableListOf<IceCandidate>()
    private val candidatesFromB = mutableListOf<IceCandidate>()

    // Each peer's own aggregated connection state, tracked separately so we
    // can combine them into one number the UI can show (see aggregateStates()).
    private var stateOfPeerA = PeerConnectionState.NEW
    private var stateOfPeerB = PeerConnectionState.NEW

    private val _uiState = MutableStateFlow(LocalPeerConnectionUiState())
    val uiState: StateFlow<LocalPeerConnectionUiState> = _uiState.asStateFlow()

    private fun appendLog(message: String) {
        _uiState.update { current -> current.copy(logs = current.logs + message) }
    }

    private fun showError(message: String) {
        appendLog("[WebRTC] ERROR: $message")
        _uiState.update { it.copy(error = message) }
    }

    fun clearError() {
        _uiState.update { it.copy(error = null) }
    }



    /**
     * STEP 1-6 of the required sequence:
     *   1. Initialize PeerConnectionFactory
     *   2. Create Peer A
     *   3. Create Peer B
     *   4. Create local media tracks
     *   5. Add tracks to Peer A
     * (step 6, createOffer, is triggered separately by onCreateOfferClicked
     * so the two are visible as distinct actions in the UI, exactly like the
     * "Create Peers" / "Create Offer" buttons in the project brief's mockup.)
     */
    fun onCreatePeersClicked() {
        if (_uiState.value.peersCreated) {
            appendLog("[WebRTC] Peers already created - ignoring duplicate click")
            return
        }
        viewModelScope.launch {
            runCatching {
                // ---- Step 1: Initialize PeerConnectionFactory ----
                webRtcManager.initialize(::appendLog)

                // ---- Step 4: Create local media tracks (camera + mic) ----
                val localVideoTrack = webRtcManager.createLocalVideoTrack(::appendLog)
                val localAudioTrack = webRtcManager.createLocalAudioTrack(::appendLog)

                // PART 4: minimal RTCConfiguration, no STUN/TURN servers -
                // see the class doc in PeerConnectionManager.kt for why an
                // empty list is correct for two peers on the same device.
                val rtcConfig = PeerConnection.RTCConfiguration(emptyList())

                // ---- Step 2: Create Peer A ----
                val newPeerConnectionA = PeerConnectionManager(
                    label = "A",
                    factory = webRtcManager.peerConnectionFactory,
                    rtcConfig = rtcConfig,
                    onIceCandidateGenerated = { candidate ->
                        candidatesFromA.add(candidate)
                        _uiState.update { it.copy(pendingIceCandidateCount = candidatesFromA.size + candidatesFromB.size) }

                        Log.d(tag, "onCreatePeersClicked - peerConnectionA - candidate: $candidate")
                    },
                    onIceConnectionStateChanged = { /* logged inside PeerConnectionManager already */ },
                    onConnectionStateChanged = { webRtcState ->
                        stateOfPeerA = webRtcState.toUiConnectionState()
                        recomputeAggregatedConnectionState()
                    },
                    // Peer A is the sender in this project - it is not expected
                    // to receive a remote video/audio track back, so these are
                    // no-ops. (Exercise 4 in the learning guide asks you to make
                    // this project bidirectional - then these would matter too.)
                    onRemoteVideoTrack = { },
                    onRemoteAudioTrack = { },
                    log = ::appendLog
                )
                peerConnectionA = newPeerConnectionA
                appendLog("[WebRTC] Peer A created")

                // ---- Step 3: Create Peer B ----
                val newPeerConnectionB = PeerConnectionManager(
                    label = "B",
                    factory = webRtcManager.peerConnectionFactory,
                    rtcConfig = rtcConfig,
                    onIceCandidateGenerated = { candidate ->
                        candidatesFromB.add(candidate)
                        _uiState.update { it.copy(pendingIceCandidateCount = candidatesFromA.size + candidatesFromB.size) }
                        Log.d(tag, "onCreatePeersClicked - peerConnectionB - candidate: ${candidate.toString()}")
                        onExchangeIceClicked()
                    },
                    onIceConnectionStateChanged = { },
                    onConnectionStateChanged = { webRtcState ->
                        stateOfPeerB = webRtcState.toUiConnectionState()
                        recomputeAggregatedConnectionState()
                    },
                    onRemoteVideoTrack = { track -> onRemoteVideoTrackReceived(track) },
                    onRemoteAudioTrack = { track -> onRemoteAudioTrackReceived(track) },
                    log = ::appendLog
                )
                peerConnectionB = newPeerConnectionB
                appendLog("[WebRTC] Peer B created")

                // ---- Step 5: Add local tracks to Peer A only ----
                // Peer B intentionally gets no local tracks added - it is a
                // receive-only peer in this project, which keeps the offer/
                // answer flow easy to reason about (see PART 6/11 comments).
                newPeerConnectionA.addLocalVideoTrack(localVideoTrack, LOCAL_STREAM_ID)
                newPeerConnectionA.addLocalAudioTrack(localAudioTrack, LOCAL_STREAM_ID)

                _uiState.update {
                    it.copy(
                        peersCreated = true,
                        hasLocalVideo = true,
                        localVideoTrack = localVideoTrack
                    )
                }
            }.onFailure { throwable ->
                showError(throwable.message ?: "Unknown error while creating peers")
            }
        }
    }

    private fun onRemoteVideoTrackReceived(track: VideoTrack) {
        appendLog("[WebRTC] Remote video track received")
        _uiState.update { it.copy(hasRemoteVideo = true, remoteVideoTrack = track) }
    }

    private fun onRemoteAudioTrackReceived(@Suppress("UNUSED_PARAMETER") track: AudioTrack) {
        // No UI needed for audio - WebRTC plays an enabled remote AudioTrack
        // through the device's speaker automatically. We only log it so the
        // full "remote media arrived" story is visible (PART 15).
        appendLog("[WebRTC] Remote audio track received")
    }

    /*** STEP 6-9 of the required sequence:
     *   6. Peer A createOffer()
     *   7. Peer A setLocalDescription(offer)
     *   8. Transfer offer A -> B          <-- SIGNALING SIMULATION
     *   9. Peer B setRemoteDescription(offer)
     */

    fun onCreateOfferClicked() {
        val peerA = peerConnectionA
        val peerB = peerConnectionB
        if (peerA == null || peerB == null) {
            showError("Press 'Create Peers' before creating an offer")
            return
        }
        viewModelScope.launch {
            runCatching {
                // Step 6
                val offer = peerA.createOffer()
                appendLog("[WebRTC] Offer created")

                // Step 7
                peerA.setLocalDescription(offer)
                appendLog("[WebRTC] Peer A local description set")

                // Step 8 - SIGNALING SIMULATION: in a real app this SDP would
                // be serialized and sent over a WebSocket/HTTP call to Peer B's
                // device. Here we just hand the same object to Peer B directly.
                appendLog("[WebRTC] Offer transferred from Peer A to Peer B (in-memory, no network)")

                // Step 9
                peerB.setRemoteDescription(offer)
                appendLog("[WebRTC] Peer B remote description set")

                _uiState.update { it.copy(offerAnswerExchanged = false) }
            }.onFailure { throwable ->
                showError(throwable.message ?: "Unknown error while creating the offer")
            }
        }
    }

    /**
     * STEP 10-13 of the required sequence:
     *   10. Peer B createAnswer()
     *   11. Peer B setLocalDescription(answer)
     *   12. Transfer answer B -> A         <-- SIGNALING SIMULATION
     *   13. Peer A setRemoteDescription(answer)
     */
    fun onCreateAnswerClicked() {
        val peerA = peerConnectionA
        val peerB = peerConnectionB
        if (peerA == null || peerB == null) {
            showError("Press 'Create Peers' before creating an answer")
            return
        }
        viewModelScope.launch {
            runCatching {
                // Step 10
                val answer = peerB.createAnswer()
                appendLog("[WebRTC] Answer created")

                // Step 11
                peerB.setLocalDescription(answer)
                appendLog("[WebRTC] Peer B local description set")

                // Step 12 - SIGNALING SIMULATION, same idea as the offer above,
                // just in the opposite direction (B -> A).
                appendLog("[WebRTC] Answer transferred from Peer B to Peer A (in-memory, no network)")

                // Step 13
                peerA.setRemoteDescription(answer)
                appendLog("[WebRTC] Peer A remote description set")

                _uiState.update { it.copy(offerAnswerExchanged = true) }
            }.onFailure { throwable ->
                showError(throwable.message ?: "Unknown error while creating the answer")
            }
        }
    }

    /**
     * STEP 14-15 of the required sequence:
     *   14. ICE candidates are generated (this already happened in the
     *       background - see onIceCandidateGenerated above - as soon as each
     *       peer's local description was set)
     *   15. Exchange ICE candidates       <-- SIGNALING SIMULATION
     *
     * We deliberately delay the actual `addIceCandidate()` calls until this
     * button is pressed, even though the candidates themselves were
     * generated earlier: this makes "a candidate was DISCOVERED" and "a
     * candidate was DELIVERED to the other peer" two visibly separate
     * moments, which is exactly how real, network-based signaling behaves
     * (there is always a gap between discovering a candidate locally and it
     * arriving on the other device). Pressing this button again later will
     * flush any newly-discovered candidates too.
     */
    fun onExchangeIceClicked() {
        val peerA = peerConnectionA
        val peerB = peerConnectionB
        if (peerA == null || peerB == null) {
            showError("Press 'Create Peers' before exchanging ICE candidates")
            return
        }

        val candidatesToSendToB = candidatesFromA.toList().also { candidatesFromA.clear() }
        val candidatesToSendToA = candidatesFromB.toList().also { candidatesFromB.clear() }

        candidatesToSendToB.forEach { candidate -> peerB.addRemoteIceCandidate(candidate) }
        candidatesToSendToA.forEach { candidate -> peerA.addRemoteIceCandidate(candidate) }

        appendLog(
            "[WebRTC] ICE candidate exchanged: ${candidatesToSendToB.size} A->B, " +
                "${candidatesToSendToA.size} B->A"
        )
        _uiState.update { it.copy(pendingIceCandidateCount = candidatesFromA.size + candidatesFromB.size) }

        // Steps 16-18 (connection established, remote track received, remote
        // video rendered) are NOT explicit calls here - they happen
        // automatically inside the native WebRTC engine once both peers have
        // a remote description AND at least one working candidate pair. Watch
        // the logs: `onConnectionChange`/`onAddTrack` will fire on their own.
    }

    /** PART 19/20 - full teardown, used by the "Close" button and onCleared(). */
    fun onCloseClicked() {
        peerConnectionA?.close()
        peerConnectionA?.dispose()
        peerConnectionB?.close()
        peerConnectionB?.dispose()
        peerConnectionA = null
        peerConnectionB = null
        candidatesFromA.clear()
        candidatesFromB.clear()
        stateOfPeerA = PeerConnectionState.NEW
        stateOfPeerB = PeerConnectionState.NEW

        webRtcManager.release(::appendLog)

        _uiState.update {
            LocalPeerConnectionUiState(logs = it.logs + "[WebRTC] Session closed and all resources released")
        }
    }

    private fun recomputeAggregatedConnectionState() {
        _uiState.update { it.copy(connectionState = aggregateConnectionStates(stateOfPeerA, stateOfPeerB)) }
    }

    /**
     * PART 13 - combining two independent PeerConnection states into one
     * number for the UI. There is no built-in WebRTC API for this because
     * real apps only ever look at ONE PeerConnection's state - this project
     * has two only because it is simulating both ends of the call at once.
     */
    private fun aggregateConnectionStates(a: PeerConnectionState, b: PeerConnectionState): PeerConnectionState = when {
        a == PeerConnectionState.FAILED || b == PeerConnectionState.FAILED -> PeerConnectionState.FAILED
        a == PeerConnectionState.CLOSED || b == PeerConnectionState.CLOSED -> PeerConnectionState.CLOSED
        a == PeerConnectionState.CONNECTED && b == PeerConnectionState.CONNECTED -> PeerConnectionState.CONNECTED
        a == PeerConnectionState.DISCONNECTED || b == PeerConnectionState.DISCONNECTED -> PeerConnectionState.DISCONNECTED
        a == PeerConnectionState.CONNECTING || b == PeerConnectionState.CONNECTING ||
            a == PeerConnectionState.CONNECTED || b == PeerConnectionState.CONNECTED -> PeerConnectionState.CONNECTING
        else -> PeerConnectionState.NEW
    }

    private fun PeerConnection.PeerConnectionState.toUiConnectionState(): PeerConnectionState = when (this) {
        PeerConnection.PeerConnectionState.NEW -> PeerConnectionState.NEW
        PeerConnection.PeerConnectionState.CONNECTING -> PeerConnectionState.CONNECTING
        PeerConnection.PeerConnectionState.CONNECTED -> PeerConnectionState.CONNECTED
        PeerConnection.PeerConnectionState.DISCONNECTED -> PeerConnectionState.DISCONNECTED
        PeerConnection.PeerConnectionState.FAILED -> PeerConnectionState.FAILED
        PeerConnection.PeerConnectionState.CLOSED -> PeerConnectionState.CLOSED
    }

    /**
     * PART 20 - Android lifecycle: `onCleared()` is called by the
     * ViewModel/AndroidViewModel framework when the ViewModelStore that owns
     * this ViewModel is cleared - for a single-Activity app with default
     * navigation, that means "the Activity is finishing for good" (NOT on
     * rotation - Compose + ViewModel already survive configuration changes
     * by design, so we do not need any manual rotation handling here). This
     * is our last-resort safety net so camera/mic/native WebRTC resources are
     * never leaked even if the user never presses "Close" themselves.
     */
    override fun onCleared() {
        if (_uiState.value.peersCreated) {
            onCloseClicked()
        }
        super.onCleared()
    }
}
